### ISSUE TITLE
White text on white background

### ISSUE THREAD

**Issue by Bisaloo** [diesys/transmission-web-soft-theme#4]
Odd rows in the list of peers have white text on white background in the dark theme.

Offending lines to overwrite from `common.css`:

```css
tr.inspector_peer_entry.odd {
	background-color: #EEEEEE;
}
```

Please let me know if you'd like more info or a PR (but I'm not sure which background colour to choose. Or you can get rid of zebra lines entirely and use the same colour for all rows).
